[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = ["-C", "link-arg=-fuse-ld=lld", "-C", "link-arg=-Wl,-zstack-size=8388608"]

[target.aarch64-apple-darwin]
linker = "clang"
rustflags = [
    "-C", "link-arg=-Wl,-dead_strip",
    "-C", "link-arg=-undefined",
    "-C", "link-arg=dynamic_lookup"
]

[target.x86_64-pc-windows-msvc]
linker = "lld-link.exe"
rustflags = ["-C", "link-arg=/STACK:8388608"]